apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-configmap
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-configmap
        configMap:
          name: nginx-configmap
